# RNN

In [1]:
#导入若干工具包
import torch
import torch.nn as nn



In [2]:
#实例化rnn对象
#第一个参数：input_size (输入张量x的维度)
#第二个参数：hidden_size(隐藏层的维度，隐藏层神经元数量)
#第三个参数：num_layers(隐藏层的层数)
rnn = nn.RNN(5,6,1)


In [3]:
#设定输入张量x
#第一个参数：sequence_length(输入序列的长度)
#第二个参数：batch_size(批次的样本数)
#第三个参数：input_size(输入张量x的维度)
input1 = torch.randn(1,3,5)


In [4]:
#设定初始化的h0
#第一个参数：num_layers * num_directions (层数 * 网络方向数)
#第二个参数：batch_size(批次的样本数)
#第三个参数：hidden_size(隐藏层的维度)
h0 = torch.randn(1,3,6)

In [5]:
#输入张量放入RNN中，得到输出结果
output,hn = rnn(input1,h0)
print (output)
print(output.shape)
print(hn)
print(hn.shape)


tensor([[[ 0.2482,  0.6911, -0.2292, -0.4030, -0.3212,  0.4239],
         [ 0.1211,  0.3824, -0.8212, -0.6163,  0.6492, -0.8327],
         [ 0.2454,  0.9316, -0.8763, -0.0716,  0.9272,  0.0680]]],
       grad_fn=<StackBackward0>)
torch.Size([1, 3, 6])
tensor([[[ 0.2482,  0.6911, -0.2292, -0.4030, -0.3212,  0.4239],
         [ 0.1211,  0.3824, -0.8212, -0.6163,  0.6492, -0.8327],
         [ 0.2454,  0.9316, -0.8763, -0.0716,  0.9272,  0.0680]]],
       grad_fn=<StackBackward0>)
torch.Size([1, 3, 6])


# LSTM 构建

In [6]:
#实例化LSTM对象
#第一个参数：input_size(输入张量x的维度)
#第二个参数：hidden_size(隐藏层的维度，隐藏层神经元数量)
#第三个参数：num_layers(隐藏层的层数)
lstm = nn.LSTM(5,6,2)

In [7]:
#初始换张量x
#第一个参数：sequence_length(输入张量序列的长度)
#第二个参数：batch_size(批次的样本数量)
#第三个参数：input_size(输入张量的维度)
input = torch.randn(1,3,5)


In [8]:
#初始化隐藏层h0、细胞状态层c0
#第一个参数：num_layers * num_directions(隐藏层层数 * 方向数)
#第二个参数：batch_size(隐藏层批次的样本数)
#第三个参数：hidden_size(隐藏层的维度)
h0 = torch.randn(2,3,6)
c0 = torch.randn(2,3,6)

In [10]:
#将input、h0、c0放进LSTM中，得到输出
output,(hn,cn) = lstm(input,(h0,c0))
print(output)
print(output.shape)
print(hn)
print(hn.shape)
print(cn)
print(cn.shape)

tensor([[[ 0.0739,  0.1043, -0.2780,  0.1585,  0.1951, -0.0589],
         [-0.0552,  0.1211, -0.5487, -0.0940, -0.1131, -0.0312],
         [-0.1777, -0.2635, -0.1914, -0.0616, -0.1267, -0.3442]]],
       grad_fn=<MkldnnRnnLayerBackward0>)
torch.Size([1, 3, 6])
tensor([[[ 0.0085,  0.1104,  0.2698,  0.4050, -0.1913,  0.0654],
         [ 0.3555,  0.6217, -0.3116, -0.1159,  0.2692,  0.5050],
         [-0.4344,  0.2406,  0.0987,  0.0819, -0.2181,  0.2064]],

        [[ 0.0739,  0.1043, -0.2780,  0.1585,  0.1951, -0.0589],
         [-0.0552,  0.1211, -0.5487, -0.0940, -0.1131, -0.0312],
         [-0.1777, -0.2635, -0.1914, -0.0616, -0.1267, -0.3442]]],
       grad_fn=<StackBackward0>)
torch.Size([2, 3, 6])
tensor([[[ 0.0140,  0.3142,  1.6726,  0.9672, -0.2457,  0.1374],
         [ 0.6373,  1.0368, -0.7615, -0.4118,  0.6075,  1.5129],
         [-1.0213,  0.3504,  0.2680,  0.2369, -0.4298,  0.5401]],

        [[ 0.1237,  0.1671, -0.6017,  0.2505,  0.5422, -0.0840],
         [-0.1677,  0.2345, 

# GRU(gated recurrent unit)构建

In [11]:
#实例化GRU对象
#第一个参数：input_size(输入张量的维度)
#第二个参数：hidden_size(隐藏层的维度，隐藏层神经元的数量)
#第三个参数：num_layers(隐藏层的层数)
gru = nn.GRU(5,6,2)


In [13]:
#初始化输入张量input
#第一个参数：sequence_length(输入张量的长度)
#第二个参数：batch_size(批次的样本数)
#第三个参数：input_size(输入张量的维度)
input = torch.randn(1,3,5)


In [14]:
#初始化隐藏层h0
#第一个参数：num_layers * num_directions(隐藏层层数 * 方向数)
#第二个参数：batch_size(批次样本数)
#第三个参数：hidden_size(隐藏层的维度，隐藏层神经元的个数)
h0 = torch.randn(2,3,6)

In [15]:
#将input,h0放进GRU中,得到张量结果
output,hn = gru(input,h0)
print(output)
print(hn)
print(output.shape)
print(hn.shape)

tensor([[[-0.3540,  0.6536, -0.3639,  0.0323,  0.6439, -0.9718],
         [ 0.0772,  0.2279, -0.0382,  0.1672,  0.2908, -1.3857],
         [ 0.0114, -0.1138, -0.0125,  0.3035,  1.2135, -0.3262]]],
       grad_fn=<StackBackward0>)
tensor([[[-0.8296, -0.9264,  0.1194,  0.1818,  0.4957,  0.6590],
         [-0.5379,  0.2042, -0.1039,  0.6650,  0.4667, -0.0351],
         [-0.0673,  0.6622,  0.3283,  0.2670, -0.8153, -0.1277]],

        [[-0.3540,  0.6536, -0.3639,  0.0323,  0.6439, -0.9718],
         [ 0.0772,  0.2279, -0.0382,  0.1672,  0.2908, -1.3857],
         [ 0.0114, -0.1138, -0.0125,  0.3035,  1.2135, -0.3262]]],
       grad_fn=<StackBackward0>)
torch.Size([1, 3, 6])
torch.Size([2, 3, 6])


# 注意力机制

In [16]:
#bmm运算
a = torch.randn(10,3,4)
b = torch.randn(10,4,5)
c = torch.bmm(a,b)
print(c.size())

torch.Size([10, 3, 5])


In [4]:
#注意力机制代码分析
import torch
import torch.nn as nn
import torch.nn.functional as F
class Attn(nn.Module):
    def __init__(self,query_size,key_size,value_size1,value_size2,output_size):
        """
        初始化函数的参数有5个,query_size表示Q的最后一维大小;key_size表示K的最后一维大小;value_size1与value_size2、1拼接起来是value_size(value_size=(1,value_size1,value_size2))
        value_size1代表value的倒数第二维大小,value_size2代表value的最后一维大小;output表示输出的最后一维大小
        """
        super(Attn,self).__init__()
        #将参数传入类中
        self.query_size = query_size
        self.key_size = key_size
        self.value_size1 = value_size1
        self.value_size2 = value_size2
        self.output_size = output_size

        #初始化注意力机制计算第一步的线形层
        self.attn = nn.Linear(self.query_size + self.key_size,value_size1)

        #初始化注意力机制第三步的线性层
        self.attn_combine = nn.Linear(self.query_size +value_size2,output_size )

    def forward(self,Q,K,V):
        """
        forword函数的参数有三个：Q,K,V，根据模型训练的常识，输入给Attion机制的张量一般都是三维张量，因此假设Q,K,V也是三维张量
        """
        #按照计算规则计算
        #采用第一种方法
        #将Q,K进行纵轴拼接，再经过线性层变换，再使用softmax得到结果
        attn_weight = F.softmax(self.attn(torch.cat((Q[0],K[0]),1)),dim = 1)

        #进行第一种方法的后半部分：将得到的权重矩阵与V做矩阵乘法
        #当两者都是三维张量且第一维代表batch时，则做bmm计算
        attn_applied = torch.bmm(attn_weight.unsqueeze(0),V)

        #进行第二步，通过取[0]来降维，需要将Q与第一步计算结果再进行拼接
        output = torch.cat((Q[0],attn_applied[0]),1)

        #最后是第三步：使用线性层作用在第二步的结果上做一个线性变化扩展维度，得到输出
        #要保证输出也是三维张量，因此使用unsequeeze(0)扩展维度
        output = self.attn_combine(output).unsqueeze(0)
        return output,attn_weight
    







In [5]:
import torch
query_size = 32
key_size = 32
value_size1 = 32
value_size2 = 64
output_size = 64
attn = Attn(query_size,key_size,value_size1,value_size2,output_size)
Q = torch.randn(1,1,32)
K = torch.randn(1,1,32)
V = torch.randn(1,32,64)
out = attn(Q,K,V)
print(out[0])
print(out[1])


tensor([[[ 0.0032,  0.3092, -0.2505, -0.1692,  0.0201,  0.0073, -0.3630,
           0.6448, -0.5844,  0.3861, -0.1462,  0.0610,  0.2310, -0.4824,
           0.0357,  0.4505, -0.1351,  0.1047,  0.1009, -0.3295,  0.0391,
           0.1833,  0.1724, -0.2150, -0.3280,  0.3091,  0.6042,  0.3016,
           0.0033, -0.1250, -0.0111,  0.2098,  0.3798,  0.4182,  0.1008,
           0.0225,  0.8049,  0.1302, -0.7070,  0.0318,  0.2500, -0.3100,
          -0.1419,  0.4988,  0.0781, -0.4034, -0.1098,  0.5854,  0.0441,
           0.4562,  0.3125, -0.4676, -0.3024, -0.2297, -0.0061, -0.2875,
           0.0410, -0.2929,  0.4175,  0.4556, -0.2975,  0.2235,  0.1215,
           0.1929]]], grad_fn=<UnsqueezeBackward0>)
tensor([[0.0156, 0.0344, 0.0281, 0.0623, 0.0225, 0.0723, 0.0109, 0.0226, 0.0079,
         0.0486, 0.0149, 0.0187, 0.0187, 0.0112, 0.0395, 0.0303, 0.0322, 0.0599,
         0.0481, 0.0336, 0.0265, 0.0064, 0.0222, 0.0634, 0.0426, 0.0288, 0.0329,
         0.0496, 0.0331, 0.0259, 0.0118, 0.0245]